src/main/java/cloud/xhmy/pojo/EBooks.java
package cloud.xhmy.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.sql.Timestamp;

/**
 * 电子书
 * eBook
 * @author aliketh.xhmy
 */
public class EBooks {

    private int id;
    private String uuid;
    private String bookName;
    private String author;
    private String publishTime;
    private String language;
    private String publishHouse;
    private String shelves;
    private String coverPicture;
    private String format;
    private String introduction;
    private String classify;
    private String auditStatus;
    private String description;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Timestamp uploadTime;


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getPublishHouse() {
        return publishHouse;
    }

    public void setPublishHouse(String publishHouse) {
        this.publishHouse = publishHouse;
    }

    public String getFormat() {
        return format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public String getShelves() {
        return shelves;
    }

    public void setShelves(String shelves) {
        this.shelves = shelves;
    }

    public String getCoverPicture() {
        return coverPicture;
    }

    public void setCoverPicture(String coverPicture) {
        this.coverPicture = coverPicture;
    }

    public String getPrice() {
        return format;
    }

    public void setPrice(String format) {
        this.format = format;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getClassify() {
        return classify;
    }

    public void setClassify(String classify) {
        this.classify = classify;
    }

    public String getAuditStatus() {
        return auditStatus;
    }

    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getUploadTime() {
        return uploadTime;
    }

    public void setUploadTime(Timestamp uploadTime) {
        this.uploadTime = uploadTime;
    }
}

src/main/java/cloud/xhmy/pojo/Notes.java
package cloud.xhmy.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 笔记
 * notes
 * @author aliketh.xhmy
 */
public class Notes {

    private int id;
    private String notesName;
    private String notesContent;
    private String notesAuthor;
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date notesTime;


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNotesName() {
        return notesName;
    }

    public void setNotesName(String notesName) {
        this.notesName = notesName;
    }

    public String getNotesContent() {
        return notesContent;
    }

    public void setNotesContent(String notesContent) {
        this.notesContent = notesContent;
    }

    public String getNotesAuthor() {
        return notesAuthor;
    }

    public void setNotesAuthor(String notesAuthor) {
        this.notesAuthor = notesAuthor;
    }

    public Date getNotesTime() {
        return notesTime;
    }

    public void setNotesTime(Date notesTime) {
        this.notesTime = notesTime;
    }
}

src/main/java/cloud/xhmy/pojo/Users.java
package cloud.xhmy.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigInteger;
import java.util.Date;

/**
 * 正式用户
 * @author aliketh.xhmy
 */
public class Users {

        private int uid;
        private String email;
        private String password;
        private BigInteger telephone;
        private String sex;
        private int age;
        private String realName;
        private String altContact;
        private String usName;
        private String idNumber;
        private String location;
        private String avatar;
        private String permissions;
        private String background;
        @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
        private Date createTime;



    public int getUid() {
        return uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public BigInteger getTelephone() {
        return telephone;
    }

    public void setTelephone(BigInteger telephone) {
        this.telephone =telephone ;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getAltContact() {
        return altContact;
    }

    public void setAltContact(String altContact) {
        this.altContact = altContact;
    }

    public String getUsName() {
        return usName;
    }

    public void setUsName(String usName) {
        this.usName = usName;
    }

    public String getIdNumber() {
        return idNumber;
    }

    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getPermissions() {
        return permissions;
    }

    public void setPermissions(String permissions) {
        this.permissions = permissions;
    }

    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        createTime = new Date();
        this.createTime = createTime;
    }
}

src/main/java/cloud/xhmy/controller/NotesController.java
package cloud.xhmy.controller;

import cloud.xhmy.pojo.Notes;
import cloud.xhmy.service.NotesService;
import cloud.xhmy.util.files.FilesDelete;
import com.alibaba.fastjson.JSONObject;
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import java.io.*;
import java.util.Date;
import java.util.List;

/**
 * @author aliketh.xhmy
 */
@Controller
public class NotesController {
    @Autowired
    @Qualifier("notesServiceImpl")
    private NotesService notesService;


    /**
     * 删除笔记
     *
     * @param notesId
     * @return
     */
    @ResponseBody
    @RequestMapping("/delete/notes")
    public JSONObject notes(@RequestParam("id") List<Integer> notesId, HttpServletRequest request) {
        List<Integer> list = notesId;

        Notes notes;
        for (int i = 0; i < list.size(); i++) {
            int id = list.get(i);
            notes = notesService.queryById(id);
            FilesDelete.delete(notes.getNotesContent(), request);
            notesService.deleteById(id);
        }
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("code", "1");
        return jsonObject;

//        return "user/listNotes";
    }

    /**
     * 跳转到笔记页面
     *
     * @return
     */
    @RequestMapping("/toNotes")
    public String toNotes() {
        return "user/notes";
    }

    /**
     * 跳转到笔记修改页面
     *
     * @return
     */
    @RequestMapping("/toModifyNotes/{id}")
    public String toModifyNotes(@PathVariable int id, Model model) {
        System.out.println("====================================" + id);
        Notes notes = notesService.queryById(id);
        model.addAttribute("notes", notes);
        return "user/modifyNotes";
    }

    /**
     * 跳转到笔记预览页面
     *
     * @param id
     * @return
     */
    @RequestMapping("/toReadNotes/{id}")
    public String toReadNotes(@PathVariable int id, Model model) {


        Notes notes = notesService.queryById(id);
        model.addAttribute("notes", notes);
        return "user/readNotes";
    }

    /**
     * 列出个人所有笔记
     *
     * @param author
     * @param page
     * @param size
     * @return
     */
    @ResponseBody
    @RequestMapping("/allNotes/{user.email}")
    public ModelAndView allNotes(@PathVariable("user.email") String author, @RequestParam(defaultValue = "1") int page,
                                 @RequestParam(defaultValue = "10") int size) {
        PageHelper.startPage(page, size);
        ModelAndView mv = new ModelAndView();
        List<Notes> list = notesService.listAll(author, page, size);
        PageInfo<Notes> pageInfos = new PageInfo<>(list);
        mv.addObject("pageInfos", pageInfos);
        mv.setViewName("user/listNotes");
        return mv;
    }

    /**
     * 保存日记
     *
     * @param notes
     * @param request
     * @param model
     * @return
     * @throws IOException
     */
    @ResponseBody
    @RequestMapping("/saveNotes")
    public JSONObject saveNotes(@ModelAttribute Notes notes, HttpServletRequest request, Model model) throws IOException {

        //("/")是表示文件上传后的目标文件
        String realPath = request.getSession().getServletContext().getRealPath("/static");
        String contentPath = "/upload/notes/";
        String path = realPath + contentPath;

        //创建File对象，传入目标路径参数和文件名称
        File dir = new File(path);

        if (!dir.exists()) {  //如果dir代表的文件不存在，则创建
            dir.mkdirs();
        }
        System.out.println("===============================" + notes);

        String suffix = ".md";

        Date date = new Date();
        String fileName = date.getTime() + suffix;


        notes.setNotesContent(contentPath + fileName);
        notes.setNotesTime(new Date());
        notesService.addNotes(notes);


        String destFile = path + fileName;
        //换编码格式保存
        OutputStreamWriter os = new OutputStreamWriter(new FileOutputStream(destFile), "UTF-8");
        os.write(request.getParameter("data"));
        os.close();
        //不转换编码格式保存
//        FileWriter art = new FileWriter(destFile);
//        art.write(request.getParameter("data"));
//        art.flush();
//        art.close();


        JSONObject jsonObject = new JSONObject();
        jsonObject.put("code", "1");
        jsonObject.put("msg", "成功！");
        return jsonObject;
//        model.addAttribute("success","保存成功");
//        return "user/notes";
    }

    /**
     * 查询
     *
     * @param name
     * @param page
     * @param size
     * @return
     */
    @RequestMapping("/queryNotes/{byName}")
    public ModelAndView queryNotes(@PathVariable("byName") String name,
                                   @RequestParam(defaultValue = "1") int page,
                                   @RequestParam(defaultValue = "10") int size) {
        PageHelper.startPage(page, size);
        ModelAndView mv = new ModelAndView();
        List<Notes> list = notesService.queryByName(name, page, size);
        PageInfo<Notes> pageInfos = new PageInfo<>(list);
        mv.addObject("pageInfos", pageInfos);
        mv.setViewName("user/listNotes");
        return mv;

    }
}

web/WEB-INF/jsp/user/controller.jsp
<%--
  Created by IntelliJ IDEA.
  User: aliketh.xhmy
  Date: 2020/11/4
  Time: 21:27
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>controller</title>
    <jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/head.jsp"/>
</head>
<body>
<jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/bodyNav.jsp"/>




<jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/footer.jsp"/>
</body>
</html>

web/WEB-INF/jsp/user/index.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: aliketh.xhmy
  Date: 2020/10/25
  Time: 20:00
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>



    <jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/head.jsp" flush="true"/>

    <title>index</title>


</head>
<body>
<jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/bodyNav.jsp"/>
<div style="">

    <div style="width: 90%;margin: 5px auto;">
        <h2 style="margin: 10px auto;">欢迎[<span style="color: dodgerblue;">${user.email}</span>]</h2>
    </div>

    <div class="container">

        <div class="row" style="width: 80%;margin: 5px auto;"><h3><span>最新上传图书</span></h3></div>
        <c:forEach var="bro" items="${requestScope.get('book')}" >
           <div class="row" style=" width: 80%;margin:0 auto;background: #c7c7c7;">
<%--               <h3 class="homeMs"><span>描述</span></h3>--%>
               <div class="col-md-3" style="">
                   <img src="${pageContext.request.contextPath}/static${bro.coverPicture}"
                        alt="抱歉图片意外丢失，要图片显示请重新刷新页面"
                        style=" margin: auto; padding: 10px;width: 160px;height: 240px;"
                        onerror="this.src='${pageContext.request.contextPath}/static/upload/picture/CMLS-NO-Cover.png'">
               </div>
               <div class="col-md-9"  style="line-height: 2em;">
                   <span style="color: #3357ff"><h3>书名：<a href="${pageContext.request.contextPath}/browseBook/${bro.id}">${bro.bookName}</a></h3></span>
                   <span><smell>作者：${bro.author}</smell></span><br>
<%--                   <p>简介：${bro.introduction}</p>--%>
                   <span>出版社：${bro.publishHouse}</span><br>
                   <span>出版时间：${bro.publishTime}</span><br>
                   <span>语言：${bro.language}</span><br>
                   <span>参考价格：${bro.price}</span><br>
                   <span>类型：${bro.classify}</span>

               </div>
           </div>
        </c:forEach>




       <%--
       <div class="row">
           <h3 class="homeMs"><span>描述</span></h3>
           <div class="col-md-5" style=" ">
               <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
           </div>
           <div class="col-md-7"  style="width: auto; line-height: 2em;">
               <h3>书名：${books.bookName}</h3>
               <smell>作者：${books.author}</smell><br>
               <p>简介：${books.bookName}</p>
               <span>出版社：${books.publishHouse}</span><br>
               <span>出版时间：${books.publishTime}</span><br>
               <span>语言：${books.language}</span><br>
               <span>定价：${books.price}</span><br>
               <span>类型：${books.classify}</span>

           </div>
       </div>
       <div class="row">
           <h3 class="homeMs"><span>描述</span></h3>
           <div class="col-md-5" style=" ">
               <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
           </div>
           <div class="col-md-7"  style="width: auto; line-height: 2em;">
               <h3>书名：${books.bookName}</h3>
               <smell>作者：${books.author}</smell><br>
               <p>简介：${books.bookName}</p>
               <span>出版社：${books.publishHouse}</span><br>
               <span>出版时间：${books.publishTime}</span><br>
               <span>语言：${books.language}</span><br>
               <span>定价：${books.price}</span><br>
               <span>类型：${books.classify}</span>

           </div>
       </div>
       <div class="row">
           <h3 class="homeMs"><span>描述</span></h3>
           <div class="col-md-5" style=" ">
               <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
           </div>
           <div class="col-md-7"  style="width: auto; line-height: 2em;">
               <h3>书名：${books.bookName}</h3>
               <smell>作者：${books.author}</smell><br>
               <p>简介：${books.bookName}</p>
               <span>出版社：${books.publishHouse}</span><br>
               <span>出版时间：${books.publishTime}</span><br>
               <span>语言：${books.language}</span><br>
               <span>定价：${books.price}</span><br>
               <span>类型：${books.classify}</span>

           </div>
       </div>
       <div class="row">
           <h3 class="homeMs"><span>描述</span></h3>
           <div class="col-md-5" style=" ">
               <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
           </div>
           <div class="col-md-7"  style="width: auto; line-height: 2em;">
               <h3>书名：${books.bookName}</h3>
               <smell>作者：${books.author}</smell><br>
               <p>简介：${books.bookName}</p>
               <span>出版社：${books.publishHouse}</span><br>
               <span>出版时间：${books.publishTime}</span><br>
               <span>语言：${books.language}</span><br>
               <span>定价：${books.price}</span><br>
               <span>类型：${books.classify}</span>

           </div>
       </div>
       <div class="row">
           <h3 class="homeMs"><span>描述</span></h3>
           <div class="col-md-5" style=" ">
               <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
           </div>
           <div class="col-md-7"  style="width: auto; line-height: 2em;">
               <h3>书名：${books.bookName}</h3>
               <smell>作者：${books.author}</smell><br>
               <p>简介：${books.bookName}</p>
               <span>出版社：${books.publishHouse}</span><br>
               <span>出版时间：${books.publishTime}</span><br>
               <span>语言：${books.language}</span><br>
               <span>定价：${books.price}</span><br>
               <span>类型：${books.classify}</span>

           </div>
       </div>
       <div class="row">
           <h3 class="homeMs"><span>描述</span></h3>
           <div class="col-md-5" style=" ">
               <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
           </div>
           <div class="col-md-7"  style="width: auto; line-height: 2em;">
               <h3>书名：${books.bookName}</h3>
               <smell>作者：${books.author}</smell><br>
               <p>简介：${books.bookName}</p>
               <span>出版社：${books.publishHouse}</span><br>
               <span>出版时间：${books.publishTime}</span><br>
               <span>语言：${books.language}</span><br>
               <span>定价：${books.price}</span><br>
               <span>类型：${books.classify}</span>

           </div>
       </div>
       <div class="row">
           <h3 class="homeMs"><span>描述</span></h3>
           <div class="col-md-5" style=" ">
               <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
           </div>
           <div class="col-md-7"  style="width: auto; line-height: 2em;">
               <h3>书名：${books.bookName}</h3>
               <smell>作者：${books.author}</smell><br>
               <p>简介：${books.bookName}</p>
               <span>出版社：${books.publishHouse}</span><br>
               <span>出版时间：${books.publishTime}</span><br>
               <span>语言：${books.language}</span><br>
               <span>定价：${books.price}</span><br>
               <span>类型：${books.classify}</span>

           </div>
       </div>
       --%>
    </div>
</div>


<jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/footer.jsp"/>
</body>
</html>

web/WEB-INF/jsp/user/index1.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: aliketh.xhmy
  Date: 2020/10/22
  Time: 15:17
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>

    <title>home1</title>

    <jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/head.jsp"/>
</head>
<body>
<jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/bodyNav.jsp"/>
<div style="">

    <div>
<%--        <h2 style="text-align: center;margin: 30px auto;">欢迎[<span style="color: dodgerblue;">${user.email}</span>]</h2>--%>

    </div>

    <div class="container">

        <div class="row" style="width: 80%;margin: 5px auto;"><h3><span>最新上传电子书</span></h3></div>
        <c:forEach var="bro" items="${requestScope.get('eBook')}" >
            <div class="row" style=" width: 80%;margin:0 auto;background: #c7c7c7;">
                <div class="col-md-3" style=" ">
                    <img src="${pageContext.request.contextPath}/static${bro.coverPicture}"
                         alt="抱歉图片意外丢失，要图片显示请重新刷新页面"
                         style=" margin: auto; padding: 10px;width: 160px;height: 240px;"
                         onerror="this.src='${pageContext.request.contextPath}/static/upload/picture/CMLS-NO-Cover.png'">
                </div>
                <div class="col-md-9"  style="line-height: 2em;">
                    <h3><span>书名：<a href="${pageContext.request.contextPath}/browseEBook/${bro.id}">${bro.bookName}</a></span></h3>
                    <span><smell>作者：${bro.author}</smell></span><br>
                    <span>出版社：${bro.publishHouse}</span><br>
                    <span>出版时间：${bro.publishTime}</span><br>
                    <span>语言：${bro.language}</span><br>
                    <span>格式：${bro.format}</span><br>
                    <span>类型：${bro.classify}</span>

                </div>
            </div>
        </c:forEach>




        <%--
        <div class="row">
            <h3 class="homeMs"><span>描述</span></h3>
            <div class="col-md-5" style=" ">
                <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
            </div>
            <div class="col-md-7"  style="width: auto; line-height: 2em;">
                <h3>书名：${books.bookName}</h3>
                <smell>作者：${books.author}</smell><br>
                <p>简介：${books.bookName}</p>
                <span>出版社：${books.publishHouse}</span><br>
                <span>出版时间：${books.publishTime}</span><br>
                <span>语言：${books.language}</span><br>
                <span>定价：${books.price}</span><br>
                <span>类型：${books.classify}</span>

            </div>
        </div>
        <div class="row">
            <h3 class="homeMs"><span>描述</span></h3>
            <div class="col-md-5" style=" ">
                <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
            </div>
            <div class="col-md-7"  style="width: auto; line-height: 2em;">
                <h3>书名：${books.bookName}</h3>
                <smell>作者：${books.author}</smell><br>
                <p>简介：${books.bookName}</p>
                <span>出版社：${books.publishHouse}</span><br>
                <span>出版时间：${books.publishTime}</span><br>
                <span>语言：${books.language}</span><br>
                <span>定价：${books.price}</span><br>
                <span>类型：${books.classify}</span>

            </div>
        </div>
        <div class="row">
            <h3 class="homeMs"><span>描述</span></h3>
            <div class="col-md-5" style=" ">
                <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
            </div>
            <div class="col-md-7"  style="width: auto; line-height: 2em;">
                <h3>书名：${books.bookName}</h3>
                <smell>作者：${books.author}</smell><br>
                <p>简介：${books.bookName}</p>
                <span>出版社：${books.publishHouse}</span><br>
                <span>出版时间：${books.publishTime}</span><br>
                <span>语言：${books.language}</span><br>
                <span>定价：${books.price}</span><br>
                <span>类型：${books.classify}</span>

            </div>
        </div>
        <div class="row">
            <h3 class="homeMs"><span>描述</span></h3>
            <div class="col-md-5" style=" ">
                <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
            </div>
            <div class="col-md-7"  style="width: auto; line-height: 2em;">
                <h3>书名：${books.bookName}</h3>
                <smell>作者：${books.author}</smell><br>
                <p>简介：${books.bookName}</p>
                <span>出版社：${books.publishHouse}</span><br>
                <span>出版时间：${books.publishTime}</span><br>
                <span>语言：${books.language}</span><br>
                <span>定价：${books.price}</span><br>
                <span>类型：${books.classify}</span>

            </div>
        </div>
        <div class="row">
            <h3 class="homeMs"><span>描述</span></h3>
            <div class="col-md-5" style=" ">
                <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
            </div>
            <div class="col-md-7"  style="width: auto; line-height: 2em;">
                <h3>书名：${books.bookName}</h3>
                <smell>作者：${books.author}</smell><br>
                <p>简介：${books.bookName}</p>
                <span>出版社：${books.publishHouse}</span><br>
                <span>出版时间：${books.publishTime}</span><br>
                <span>语言：${books.language}</span><br>
                <span>定价：${books.price}</span><br>
                <span>类型：${books.classify}</span>

            </div>
        </div>
        <div class="row">
            <h3 class="homeMs"><span>描述</span></h3>
            <div class="col-md-5" style=" ">
                <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
            </div>
            <div class="col-md-7"  style="width: auto; line-height: 2em;">
                <h3>书名：${books.bookName}</h3>
                <smell>作者：${books.author}</smell><br>
                <p>简介：${books.bookName}</p>
                <span>出版社：${books.publishHouse}</span><br>
                <span>出版时间：${books.publishTime}</span><br>
                <span>语言：${books.language}</span><br>
                <span>定价：${books.price}</span><br>
                <span>类型：${books.classify}</span>

            </div>
        </div>
        <div class="row">
            <h3 class="homeMs"><span>描述</span></h3>
            <div class="col-md-5" style=" ">
                <img src="${pageContext.request.contextPath}/static${books.coverPicture}" alt="" style=" margin: auto; padding: 10px;">
            </div>
            <div class="col-md-7"  style="width: auto; line-height: 2em;">
                <h3>书名：${books.bookName}</h3>
                <smell>作者：${books.author}</smell><br>
                <p>简介：${books.bookName}</p>
                <span>出版社：${books.publishHouse}</span><br>
                <span>出版时间：${books.publishTime}</span><br>
                <span>语言：${books.language}</span><br>
                <span>定价：${books.price}</span><br>
                <span>类型：${books.classify}</span>

            </div>
        </div>
        --%>
    </div>

</div>
<jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/footer.jsp"/>
</body>
</html>

web/WEB-INF/jsp/user/setting.jsp
<%--
  Created by IntelliJ IDEA.
  User: aliketh.xhmy
  Date: 2020/10/24
  Time: 17:37
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>setting</title>
    <jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/head.jsp"/>
</head>
<body>
<jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/bodyNav.jsp"/>




<jsp:include page="${pageContext.request.contextPath}/WEB-INF/jsp/template/footer.jsp"/>
</body>
</html>